# Generated by Django 5.1.1 on 2024-09-17 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.subject'),
        ),
    ]
