# Generated by Django 5.1.1 on 2024-09-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_remove_exam_subject_exam_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='ball',
        ),
        migrations.AddField(
            model_name='student',
            name='ball',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
